### ISSUE TITLE
not being able to install it

### ISSUE THREAD

**Issue by mhmdmsnr** [patrick--/simplemap#8]
i have a problem installing the library (after installing all the requirements). Python still doesn't recognize the library when imported

PS: i have python 3.5.1 64-bit on win7

thx in advance

**Comment by ptrks** [comment]
Hi mhmdmsnr,

Try installing from the most recent development branch.

**Comment by ptrks** [comment]
@mhmdmsnr Any update on if the development branch changes anything?

**Comment by mhmdmsnr** [comment]
@patrick-- actually it work out for me and there for i had to use another library called folium which pretty much does the same job for me. thx anyways :)
