### ISSUE TITLE
Is there a port of this to python3?

### ISSUE THREAD

**Issue by roesel** [patrick--/simplemap#9]
I would love to use this library but I have recently switched to python3 completely. It would be useful for me to incorporate this library into a static website generator in py3.5. 

Thank you for any information on this topic.

**Comment by HFulcher** [comment]
As far as I know it is compatible with python3 (I contributed a merge that future proofed some parts), give it a try and see!

**Comment by roesel** [comment]
I tried running something that works flawlessly in Python 2 in Python 3 and I got this error:

```
File "C:\BTSync\Projects\Simplemap\simplemap_links\simplemap\__init__.py", line 1, in <module>
    from .map import Map
File "C:\BTSync\Projects\Simplemap\simplemap_links\simplemap\map.py", line 55
    print "An unknown error occured while attempting to read {} config file.".format(config_file)
                                                                            ^
SyntaxError: invalid syntax
```

If you happen to know how to fix this, let me know. Possibly a problem with "print x" as opposed to "print(x)", but there's probably a different problem if what the code is trying to print out is an error :).

**Comment by ptrks** [comment]
@roesel The 2-3 changes needed were in the develop, not the master branch. I've merged the two so you should now be good to go.
